### ISSUE TITLE
Update the documentation. Describe config values

### ISSUE THREAD

**Issue by salemgolemugoo** [jpbede/loki-auth-proxy#4]
Could you please describe configuration values behind the "backend"

```
    backend:
      distributor: distributor:3100
      query_frontend: query-frontend:3100
      querier: ws://querier:3100
```
